### ISSUE TITLE
IUserRoleMembershipService or Decorator

### ISSUE THREAD

**Issue by pauldbentley** [DevBetterCom/DevBetterWeb#142]
Hi Steve,

I understand why you have the `IUserRoleMembershipService` service - it essentially adds/removes users from a role having checked that the role and the user exist.

I recently listened to your podcast covering the Decorator pattern and wondered if this was a place it could be potentially used?

E.g. have a `UserManagerWithDomainEventsDecorator` - so that your controller can just request a `UserManager<ApplicationUser>` and call `AddToRole` without needing the service, and the domain events will be raised?  Or is this a bad use of the pattern?

**Comment by ardalis** [comment]
I wouldn't go that route in this case mainly because I would always rather depend on my own interface than on a third party interface. Reducing the surface area of my app that depends on `UserManager<T>` instead of my own interface is a net gain IMO. I'm fine to use `UserManager<T>` in my own interface's implementation but if I keep it there then I only need to change things in one place, not a bunch of different controllers/pages that reference the other type.

Now, if UserManager were my own class and it was doing its thing but I also wanted to raise some events, then certainly I could use a decorator over it. Or if the events were very specific to a given application, I might use an Application Service (just another interface/implementation, but at the application level of abstraction) to do it. Both of these would keep me from having to add responsibility to my UserManager class and help me follow OCP for that class as well.

Does that help?

**Comment by pauldbentley** [comment]
Yes that helps, thank you for your thoughts.
