### ISSUE TITLE
Member name on entity or Identity

### ISSUE THREAD

**Issue by pauldbentley** [DevBetterCom/DevBetterWeb#143]
I always get stuck on where to put forename/surname properties - I see in this project you have it on the `Member` entity.  It could also go on `ApplicationUser`, or directly into Claims I guess.  Is there a general rule to follow?

**Comment by ardalis** [comment]
My *personal* preference is not to put anything on ApplicationUser because I don't really "own" that type. If I'm using .NET Core Identity, that's really that framework's type, even though I may have a class modeling it in my model for convenience. Anything I care about as part of my model I try to put on my own type, ideally with a less-generic name than "user" (Customer, Member, Subscriber, etc).

**Comment by pauldbentley** [comment]
I follow. So if you needed a Member to have a phone number, would you take
this from Identity or again add it to Member?

Similarly with Email as this is already in Identity.

**Comment by ardalis** [comment]
If I need it for identity and it's already there, I'd use it from there to avoid data duplication, I think. If I don't (yet) need it for identity, I'd put it on `Member` or some other domain model type. In this case, email is already on the Identity type so I'd probably leave it there; phone isn't (that I recall) so unless I started requiring 2FA via SMS (which is unlikely) I would put phone info with other Member details on Member.
