### ISSUE TITLE
Display Video in a Player in the Browser

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#32]
Determine how to display the video in a player in the browser.

Desired features:

- Jump to timestamp via URL parameter (e.g. ?t=123 )
- Adjust playback speed
- Stream video content

**Comment by Joe-LaRue** [comment]
have some of this functionality implemented with azure media player.  the jump-to-timestamp stuff is depended on hard coded anchor tags in the markdown with a class of "ts"

Also, for the case where you want to click on the time stamp for a question form the questions page - started working on that by passing in a query string, but currently unable to test that because of an issue with the video I have been using to test playback

**Comment by Joe-LaRue** [comment]
It looks like there is some issue with video playback in chrome.  One thing to note is that azure media player does work in chrome, as can be seen at [https://ampdemo.azureedge.net/azuremediaplayer.html](https://ampdemo.azureedge.net/azuremediaplayer.html) .  The video at that page uses azure media services and points to a manifest file, though, and not an MP4 on blobl storage as we are currently doing.  maybe this issue will be fixed if we use media services?

**Comment by ardalis** [comment]
Azure Media Services and Streaming demo code:
https://aka.ms/build-streaming
and presentation
https://azure.microsoft.com/en-us/resources/videos/media-streaming-apps-with-azure-and-xamarin/

**Comment by Joe-LaRue** [comment]
some info about setting up azure media services and uploading/encoding in this video [https://youtu.be/8SndwAymPes](https://youtu.be/8SndwAymPes)

**Comment by ardalis** [comment]
Options:
Office365 Microsoft Stream was another option
Vimeo
Private YouTube

**Comment by ShadyNagy** [comment]
Vimeo applied
