### ISSUE TITLE
Leaderboard Ranking Needs To Sort Results Within Rank 

### ISSUE THREAD

**Issue by rickhodder** [DevBetterCom/DevBetterWeb#333]
The member and  alumni lists need to be sorted in last name + first name order within rank.
The book list needs to be ordered by title alphabetically within rank

**Comment by ardalis** [comment]
Yes. I thought it did already but if not, yes.

**Comment by ardalis** [comment]
For some ideas you can check out @snowfrogdev 's implementation of the kata here:
https://github.com/ardalis/kata-catalog/blob/main/IMPLEMENTATIONS.md

I've updated the instructions a bit since he recorded his version, but you could do the kata yourself and then probably borrow a lot of your result to use here.

**Comment by ardalis** [comment]
This seems to be done so closing.
